/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RerouteCollection
    /// </summary>
    [DataContract]
    public partial class RerouteCollection :  IEquatable<RerouteCollection>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RerouteCollection" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RerouteCollection() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RerouteCollection" /> class.
        /// </summary>
        /// <param name="userName">userName (required).</param>
        /// <param name="reroutes">reroutes (required).</param>
        public RerouteCollection(string userName = default(string), List<Reroute> reroutes = default(List<Reroute>))
        {
            // to ensure "userName" is required (not null)
            if (userName == null)
            {
                throw new InvalidDataException("userName is a required property for RerouteCollection and cannot be null");
            }
            else
            {
                this.UserName = userName;
            }

            // to ensure "reroutes" is required (not null)
            if (reroutes == null)
            {
                throw new InvalidDataException("reroutes is a required property for RerouteCollection and cannot be null");
            }
            else
            {
                this.Reroutes = reroutes;
            }

        }
        
        /// <summary>
        /// Gets or Sets UserName
        /// </summary>
        [DataMember(Name="userName", EmitDefaultValue=false)]
        public string UserName { get; set; }

        /// <summary>
        /// Gets or Sets Reroutes
        /// </summary>
        [DataMember(Name="reroutes", EmitDefaultValue=false)]
        public List<Reroute> Reroutes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RerouteCollection {\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  Reroutes: ").Append(Reroutes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RerouteCollection);
        }

        /// <summary>
        /// Returns true if RerouteCollection instances are equal
        /// </summary>
        /// <param name="input">Instance of RerouteCollection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RerouteCollection input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UserName == input.UserName ||
                    (this.UserName != null &&
                    this.UserName.Equals(input.UserName))
                ) && 
                (
                    this.Reroutes == input.Reroutes ||
                    this.Reroutes != null &&
                    input.Reroutes != null &&
                    this.Reroutes.SequenceEqual(input.Reroutes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UserName != null)
                    hashCode = hashCode * 59 + this.UserName.GetHashCode();
                if (this.Reroutes != null)
                    hashCode = hashCode * 59 + this.Reroutes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
