version: '3.7'
services:

  victorops-api-backend:
    container_name: victorops-api-backend
    image: raulchall/victorops-grafana-ds-backend:latest
    build:
      context: victorops-api-backend
      dockerfile: src/Dockerfile
    env_file:
      - victorops-api-backend/src/service/envvars
    networks:
      - vo-grafana-datasource
    ports:
      - "32834:80"
  
  postgresql-db:
    container_name: "my_postgres"
    image: "postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=VictorOpsMetadataDb
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - vo-grafana-datasource
  
  redis:
    image: redis
    container_name: task-broker-redis
    networks:
      - vo-grafana-datasource
    ports:
      - 6379
  
  grafana:
    container_name: grafana
    image: tins/grafana-victorops-plugin:latest
    build:
      context: grafana
      dockerfile: Dockerfile
      args:
        GRAFANA_VERSION: 'latest'
        GF_INSTALL_PLUGINS: 'grafana-simple-json-datasource'
    networks:
      - vo-grafana-datasource
    ports:
      - "3306"
      - "32793:3000"

networks:
  vo-grafana-datasource:
    external:
      name: vo-grafana-datasource

volumes:
  grafana-storage:
  postgres-data: