version: '3.7'
services:

  simple-json-backend:
    container_name: simple-json-backend
    image: tins/simple-json-backend:latest
    build:
      context: backends/grafana-simple-json-backend
      dockerfile: Dockerfile
    networks:
      - vo-grafana-plugin
    ports:
      - "3333"
  
  victorops-api-backend:
    container_name: victorops-api-backend
    image: tins/victorops-api-backend:latest
    build:
      context: backends/victorops-api-backend
      dockerfile: src/Dockerfile
    env_file:
      - backends/victorops-api-backend/src/service/envvars
    networks:
      - vo-grafana-plugin
    ports:
      - "32834:80"
  
  redis:
    image: redis
    container_name: task-broker-redis
    networks:
      - vo-grafana-plugin
    ports:
      - 6379
  
  grafana:
    container_name: grafana
    image: tins/grafana-victorops-plugin:latest
    build:
      context: grafana
      dockerfile: Dockerfile
      args:
        GRAFANA_VERSION: 'latest'
        GF_INSTALL_PLUGINS: 'grafana-simple-json-datasource,ryantxu-ajax-panel'
    networks:
      - vo-grafana-plugin
    ports:
      - "3306"
      - "32793:3000"

networks:
  vo-grafana-plugin:
    external:
      name: vo-grafana-plugin

volumes:
  grafana-storage: