version: '3.7'
services:

  simple-json-backend:
    container_name: simple-json-backend
    image: tins/simple-json-backend:latest
    build:
      context: backends/grafana-simple-json-backend
      dockerfile: Dockerfile
    networks:
      - vo-grafana-plugin
    ports:
      - "3333"
  
  grafana:
    container_name: grafana
    image: tins/grafana-victorops-plugin:latest
    build:
      context: .
      dockerfile: grafana/Dockerfile
      args:
        GRAFANA_VERSION: 'latest'
        GF_INSTALL_PLUGINS: 'grafana-simple-json-datasource'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./plugins:/public/app/plugins/datasource/
    networks:
      - vo-grafana-plugin
    ports:
      - "3306"
      - "3000"

networks:
  vo-grafana-plugin:
    external:
      name: vo-grafana-plugin

volumes:
  grafana-storage: