/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PersonalPagingPolicyValuesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PersonalPagingPolicyValuesApiTests : IDisposable
    {
        private PersonalPagingPolicyValuesApi instance;

        public PersonalPagingPolicyValuesApiTests()
        {
            instance = new PersonalPagingPolicyValuesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PersonalPagingPolicyValuesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PersonalPagingPolicyValuesApi
            //Assert.IsType(typeof(PersonalPagingPolicyValuesApi), instance, "instance is a PersonalPagingPolicyValuesApi");
        }

        
        /// <summary>
        /// Test ApiPublicV1PoliciesTypesContactsGet
        /// </summary>
        [Fact]
        public void ApiPublicV1PoliciesTypesContactsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //var response = instance.ApiPublicV1PoliciesTypesContactsGet(xVOApiId, xVOApiKey);
            //Assert.IsType<InlineResponse2001> (response, "response is InlineResponse2001");
        }
        
        /// <summary>
        /// Test ApiPublicV1PoliciesTypesNotificationsGet
        /// </summary>
        [Fact]
        public void ApiPublicV1PoliciesTypesNotificationsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //var response = instance.ApiPublicV1PoliciesTypesNotificationsGet(xVOApiId, xVOApiKey);
            //Assert.IsType<InlineResponse200> (response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test ApiPublicV1PoliciesTypesTimeoutsGet
        /// </summary>
        [Fact]
        public void ApiPublicV1PoliciesTypesTimeoutsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //var response = instance.ApiPublicV1PoliciesTypesTimeoutsGet(xVOApiId, xVOApiKey);
            //Assert.IsType<InlineResponse2002> (response, "response is InlineResponse2002");
        }
        
    }

}
