/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PersonalPagingPoliciesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PersonalPagingPoliciesApiTests : IDisposable
    {
        private PersonalPagingPoliciesApi instance;

        public PersonalPagingPoliciesApiTests()
        {
            instance = new PersonalPagingPoliciesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PersonalPagingPoliciesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PersonalPagingPoliciesApi
            //Assert.IsType(typeof(PersonalPagingPoliciesApi), instance, "instance is a PersonalPagingPoliciesApi");
        }

        
        /// <summary>
        /// Test ApiPublicV1ProfileUsernamePoliciesGet
        /// </summary>
        [Fact]
        public void ApiPublicV1ProfileUsernamePoliciesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //var response = instance.ApiPublicV1ProfileUsernamePoliciesGet(username, xVOApiId, xVOApiKey);
            //Assert.IsType<InlineResponse2003> (response, "response is InlineResponse2003");
        }
        
        /// <summary>
        /// Test ApiPublicV1ProfileUsernamePoliciesPost
        /// </summary>
        [Fact]
        public void ApiPublicV1ProfileUsernamePoliciesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //AddGroupPayload body = null;
            //var response = instance.ApiPublicV1ProfileUsernamePoliciesPost(username, xVOApiId, xVOApiKey, body);
            //Assert.IsType<InlineResponse2004> (response, "response is InlineResponse2004");
        }
        
        /// <summary>
        /// Test ApiPublicV1ProfileUsernamePoliciesStepGet
        /// </summary>
        [Fact]
        public void ApiPublicV1ProfileUsernamePoliciesStepGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //decimal step = null;
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //var response = instance.ApiPublicV1ProfileUsernamePoliciesStepGet(username, step, xVOApiId, xVOApiKey);
            //Assert.IsType<InlineResponse2004> (response, "response is InlineResponse2004");
        }
        
        /// <summary>
        /// Test ApiPublicV1ProfileUsernamePoliciesStepPost
        /// </summary>
        [Fact]
        public void ApiPublicV1ProfileUsernamePoliciesStepPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //decimal step = null;
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //AddStepPayload body = null;
            //var response = instance.ApiPublicV1ProfileUsernamePoliciesStepPost(username, step, xVOApiId, xVOApiKey, body);
            //Assert.IsType<InlineResponse2005> (response, "response is InlineResponse2005");
        }
        
        /// <summary>
        /// Test ApiPublicV1ProfileUsernamePoliciesStepPut
        /// </summary>
        [Fact]
        public void ApiPublicV1ProfileUsernamePoliciesStepPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //decimal step = null;
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //AddGroupPayload body = null;
            //var response = instance.ApiPublicV1ProfileUsernamePoliciesStepPut(username, step, xVOApiId, xVOApiKey, body);
            //Assert.IsType<InlineResponse2004> (response, "response is InlineResponse2004");
        }
        
        /// <summary>
        /// Test ApiPublicV1ProfileUsernamePoliciesStepRuleDelete
        /// </summary>
        [Fact]
        public void ApiPublicV1ProfileUsernamePoliciesStepRuleDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //decimal step = null;
            //decimal rule = null;
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //var response = instance.ApiPublicV1ProfileUsernamePoliciesStepRuleDelete(username, step, rule, xVOApiId, xVOApiKey);
            //Assert.IsType<InlineResponse2005> (response, "response is InlineResponse2005");
        }
        
        /// <summary>
        /// Test ApiPublicV1ProfileUsernamePoliciesStepRuleGet
        /// </summary>
        [Fact]
        public void ApiPublicV1ProfileUsernamePoliciesStepRuleGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //decimal step = null;
            //decimal rule = null;
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //var response = instance.ApiPublicV1ProfileUsernamePoliciesStepRuleGet(username, step, rule, xVOApiId, xVOApiKey);
            //Assert.IsType<InlineResponse2005> (response, "response is InlineResponse2005");
        }
        
        /// <summary>
        /// Test ApiPublicV1ProfileUsernamePoliciesStepRulePut
        /// </summary>
        [Fact]
        public void ApiPublicV1ProfileUsernamePoliciesStepRulePutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //decimal step = null;
            //decimal rule = null;
            //string xVOApiId = null;
            //string xVOApiKey = null;
            //AddStepPayload body = null;
            //var response = instance.ApiPublicV1ProfileUsernamePoliciesStepRulePut(username, step, rule, xVOApiId, xVOApiKey, body);
            //Assert.IsType<InlineResponse2005> (response, "response is InlineResponse2005");
        }
        
    }

}
