/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OnCallAndOverrides
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OnCallAndOverridesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OnCallAndOverrides
        //private OnCallAndOverrides instance;

        public OnCallAndOverridesTests()
        {
            // TODO uncomment below to create an instance of OnCallAndOverrides
            //instance = new OnCallAndOverrides();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OnCallAndOverrides
        /// </summary>
        [Fact]
        public void OnCallAndOverridesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OnCallAndOverrides
            //Assert.IsInstanceOfType<OnCallAndOverrides> (instance, "variable 'instance' is a OnCallAndOverrides");
        }


        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Fact]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }
        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Fact]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }
        /// <summary>
        /// Test the property 'Overrides'
        /// </summary>
        [Fact]
        public void OverridesTest()
        {
            // TODO unit test for the property 'Overrides'
        }

    }

}
