/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines ContactDescription
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ContactDescription
    {
        /// <summary>
        /// Enum EmailAddress for value: Email Address
        /// </summary>
        [EnumMember(Value = "Email Address")]
        EmailAddress = 1,

        /// <summary>
        /// Enum PhoneNumber for value: Phone Number
        /// </summary>
        [EnumMember(Value = "Phone Number")]
        PhoneNumber = 2

    }

}
