/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines NotificationDescription
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum NotificationDescription
    {
        /// <summary>
        /// Enum Sendapushnotificationtoallmydevices for value: Send a push notification to all my devices
        /// </summary>
        [EnumMember(Value = "Send a push notification to all my devices")]
        Sendapushnotificationtoallmydevices = 1,

        /// <summary>
        /// Enum Sendanemailtoanemailaddress for value: Send an email to an email address
        /// </summary>
        [EnumMember(Value = "Send an email to an email address")]
        Sendanemailtoanemailaddress = 2,

        /// <summary>
        /// Enum SendanSMStoaphonenumber for value: Send an SMS to a phone number
        /// </summary>
        [EnumMember(Value = "Send an SMS to a phone number")]
        SendanSMStoaphonenumber = 3,

        /// <summary>
        /// Enum Makeaphonecalltoaphonenumber for value: Make a phone call to a phone number
        /// </summary>
        [EnumMember(Value = "Make a phone call to a phone number")]
        Makeaphonecalltoaphonenumber = 4

    }

}
