/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Reroute
    /// </summary>
    [DataContract]
    public partial class Reroute :  IEquatable<Reroute>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Reroute" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Reroute() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Reroute" /> class.
        /// </summary>
        /// <param name="incidentNumber">incidentNumber (required).</param>
        /// <param name="targets">targets (required).</param>
        /// <param name="addTargets">addTargets.</param>
        public Reroute(string incidentNumber = default(string), List<IncidentTarget> targets = default(List<IncidentTarget>), bool addTargets = default(bool))
        {
            // to ensure "incidentNumber" is required (not null)
            if (incidentNumber == null)
            {
                throw new InvalidDataException("incidentNumber is a required property for Reroute and cannot be null");
            }
            else
            {
                this.IncidentNumber = incidentNumber;
            }

            // to ensure "targets" is required (not null)
            if (targets == null)
            {
                throw new InvalidDataException("targets is a required property for Reroute and cannot be null");
            }
            else
            {
                this.Targets = targets;
            }

            this.AddTargets = addTargets;
        }
        
        /// <summary>
        /// Gets or Sets IncidentNumber
        /// </summary>
        [DataMember(Name="incidentNumber", EmitDefaultValue=false)]
        public string IncidentNumber { get; set; }

        /// <summary>
        /// Gets or Sets Targets
        /// </summary>
        [DataMember(Name="targets", EmitDefaultValue=false)]
        public List<IncidentTarget> Targets { get; set; }

        /// <summary>
        /// Gets or Sets AddTargets
        /// </summary>
        [DataMember(Name="addTargets", EmitDefaultValue=false)]
        public bool AddTargets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Reroute {\n");
            sb.Append("  IncidentNumber: ").Append(IncidentNumber).Append("\n");
            sb.Append("  Targets: ").Append(Targets).Append("\n");
            sb.Append("  AddTargets: ").Append(AddTargets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Reroute);
        }

        /// <summary>
        /// Returns true if Reroute instances are equal
        /// </summary>
        /// <param name="input">Instance of Reroute to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Reroute input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IncidentNumber == input.IncidentNumber ||
                    (this.IncidentNumber != null &&
                    this.IncidentNumber.Equals(input.IncidentNumber))
                ) && 
                (
                    this.Targets == input.Targets ||
                    this.Targets != null &&
                    input.Targets != null &&
                    this.Targets.SequenceEqual(input.Targets)
                ) && 
                (
                    this.AddTargets == input.AddTargets ||
                    this.AddTargets.Equals(input.AddTargets)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IncidentNumber != null)
                    hashCode = hashCode * 59 + this.IncidentNumber.GetHashCode();
                if (this.Targets != null)
                    hashCode = hashCode * 59 + this.Targets.GetHashCode();
                hashCode = hashCode * 59 + this.AddTargets.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
