/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TakeRequest
    /// </summary>
    [DataContract]
    public partial class TakeRequest :  IEquatable<TakeRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TakeRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TakeRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TakeRequest" /> class.
        /// </summary>
        /// <param name="fromUser">fromUser (required).</param>
        /// <param name="toUser">toUser (required).</param>
        public TakeRequest(string fromUser = default(string), string toUser = default(string))
        {
            // to ensure "fromUser" is required (not null)
            if (fromUser == null)
            {
                throw new InvalidDataException("fromUser is a required property for TakeRequest and cannot be null");
            }
            else
            {
                this.FromUser = fromUser;
            }

            // to ensure "toUser" is required (not null)
            if (toUser == null)
            {
                throw new InvalidDataException("toUser is a required property for TakeRequest and cannot be null");
            }
            else
            {
                this.ToUser = toUser;
            }

        }
        
        /// <summary>
        /// Gets or Sets FromUser
        /// </summary>
        [DataMember(Name="fromUser", EmitDefaultValue=false)]
        public string FromUser { get; set; }

        /// <summary>
        /// Gets or Sets ToUser
        /// </summary>
        [DataMember(Name="toUser", EmitDefaultValue=false)]
        public string ToUser { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TakeRequest {\n");
            sb.Append("  FromUser: ").Append(FromUser).Append("\n");
            sb.Append("  ToUser: ").Append(ToUser).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TakeRequest);
        }

        /// <summary>
        /// Returns true if TakeRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TakeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TakeRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FromUser == input.FromUser ||
                    (this.FromUser != null &&
                    this.FromUser.Equals(input.FromUser))
                ) && 
                (
                    this.ToUser == input.ToUser ||
                    (this.ToUser != null &&
                    this.ToUser.Equals(input.ToUser))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FromUser != null)
                    hashCode = hashCode * 59 + this.FromUser.GetHashCode();
                if (this.ToUser != null)
                    hashCode = hashCode * 59 + this.ToUser.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
