/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A list of team admins for the team
    /// </summary>
    [DataContract]
    public partial class TeamAdminsResponse :  IEquatable<TeamAdminsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TeamAdminsResponse" /> class.
        /// </summary>
        /// <param name="teamAdmins">teamAdmins.</param>
        public TeamAdminsResponse(List<TeamAdmin> teamAdmins = default(List<TeamAdmin>))
        {
            this.TeamAdmins = teamAdmins;
        }
        
        /// <summary>
        /// Gets or Sets TeamAdmins
        /// </summary>
        [DataMember(Name="teamAdmins", EmitDefaultValue=false)]
        public List<TeamAdmin> TeamAdmins { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TeamAdminsResponse {\n");
            sb.Append("  TeamAdmins: ").Append(TeamAdmins).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TeamAdminsResponse);
        }

        /// <summary>
        /// Returns true if TeamAdminsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TeamAdminsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TeamAdminsResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TeamAdmins == input.TeamAdmins ||
                    this.TeamAdmins != null &&
                    input.TeamAdmins != null &&
                    this.TeamAdmins.SequenceEqual(input.TeamAdmins)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TeamAdmins != null)
                    hashCode = hashCode * 59 + this.TeamAdmins.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
