{
 "title": "VictorOps Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "team", "label": "Team", "query": "team" }
  ]
 },
 "panels": [
  {
   "title": "Teams",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "target": "teams", "type": "table" }
   ]
  },
  {
   "title": "Users on $team team(s)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "target": "users{team=$team}", "type": "table" }
   ]
  },
  {
   "title": "On Call on $team team(s)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "target": "oncall{team=$team}", "type": "table" }
   ]
  }
 ]
}