/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20010
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse20010Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20010
        //private InlineResponse20010 instance;

        public InlineResponse20010Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse20010
            //instance = new InlineResponse20010();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse20010
        /// </summary>
        [Fact]
        public void InlineResponse20010InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20010
            //Assert.IsInstanceOfType<InlineResponse20010> (instance, "variable 'instance' is a InlineResponse20010");
        }


        /// <summary>
        /// Test the property 'Override'
        /// </summary>
        [Fact]
        public void OverrideTest()
        {
            // TODO unit test for the property 'Override'
        }
        /// <summary>
        /// Test the property 'SelfUrl'
        /// </summary>
        [Fact]
        public void SelfUrlTest()
        {
            // TODO unit test for the property 'SelfUrl'
        }

    }

}
