/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OnCallOverride
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OnCallOverrideTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OnCallOverride
        //private OnCallOverride instance;

        public OnCallOverrideTests()
        {
            // TODO uncomment below to create an instance of OnCallOverride
            //instance = new OnCallOverride();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OnCallOverride
        /// </summary>
        [Fact]
        public void OnCallOverrideInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OnCallOverride
            //Assert.IsInstanceOfType<OnCallOverride> (instance, "variable 'instance' is a OnCallOverride");
        }


        /// <summary>
        /// Test the property 'OrigOnCallUser'
        /// </summary>
        [Fact]
        public void OrigOnCallUserTest()
        {
            // TODO unit test for the property 'OrigOnCallUser'
        }
        /// <summary>
        /// Test the property 'OverrideOnCallUser'
        /// </summary>
        [Fact]
        public void OverrideOnCallUserTest()
        {
            // TODO unit test for the property 'OverrideOnCallUser'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Fact]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }

    }

}
