/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing RerouteStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RerouteStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RerouteStatus
        //private RerouteStatus instance;

        public RerouteStatusTests()
        {
            // TODO uncomment below to create an instance of RerouteStatus
            //instance = new RerouteStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RerouteStatus
        /// </summary>
        [Fact]
        public void RerouteStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RerouteStatus
            //Assert.IsInstanceOfType<RerouteStatus> (instance, "variable 'instance' is a RerouteStatus");
        }


        /// <summary>
        /// Test the property 'IncidentNumber'
        /// </summary>
        [Fact]
        public void IncidentNumberTest()
        {
            // TODO unit test for the property 'IncidentNumber'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'TargetStatus'
        /// </summary>
        [Fact]
        public void TargetStatusTest()
        {
            // TODO unit test for the property 'TargetStatus'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
