/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ScheduledOverride
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduledOverrideTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScheduledOverride
        //private ScheduledOverride instance;

        public ScheduledOverrideTests()
        {
            // TODO uncomment below to create an instance of ScheduledOverride
            //instance = new ScheduledOverride();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScheduledOverride
        /// </summary>
        [Fact]
        public void ScheduledOverrideInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScheduledOverride
            //Assert.IsInstanceOfType<ScheduledOverride> (instance, "variable 'instance' is a ScheduledOverride");
        }


        /// <summary>
        /// Test the property 'PublicId'
        /// </summary>
        [Fact]
        public void PublicIdTest()
        {
            // TODO unit test for the property 'PublicId'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Fact]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'Assignments'
        /// </summary>
        [Fact]
        public void AssignmentsTest()
        {
            // TODO unit test for the property 'Assignments'
        }

    }

}
