/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TeamScheduleResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamScheduleResourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamScheduleResource
        //private TeamScheduleResource instance;

        public TeamScheduleResourceTests()
        {
            // TODO uncomment below to create an instance of TeamScheduleResource
            //instance = new TeamScheduleResource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamScheduleResource
        /// </summary>
        [Fact]
        public void TeamScheduleResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamScheduleResource
            //Assert.IsInstanceOfType<TeamScheduleResource> (instance, "variable 'instance' is a TeamScheduleResource");
        }


        /// <summary>
        /// Test the property 'Oncall'
        /// </summary>
        [Fact]
        public void OncallTest()
        {
            // TODO unit test for the property 'Oncall'
        }
        /// <summary>
        /// Test the property 'Overrideoncall'
        /// </summary>
        [Fact]
        public void OverrideoncallTest()
        {
            // TODO unit test for the property 'Overrideoncall'
        }
        /// <summary>
        /// Test the property 'PolicyType'
        /// </summary>
        [Fact]
        public void PolicyTypeTest()
        {
            // TODO unit test for the property 'PolicyType'
        }
        /// <summary>
        /// Test the property 'RotationName'
        /// </summary>
        [Fact]
        public void RotationNameTest()
        {
            // TODO unit test for the property 'RotationName'
        }
        /// <summary>
        /// Test the property 'ShiftName'
        /// </summary>
        [Fact]
        public void ShiftNameTest()
        {
            // TODO unit test for the property 'ShiftName'
        }
        /// <summary>
        /// Test the property 'ShiftRoll'
        /// </summary>
        [Fact]
        public void ShiftRollTest()
        {
            // TODO unit test for the property 'ShiftRoll'
        }
        /// <summary>
        /// Test the property 'Rolls'
        /// </summary>
        [Fact]
        public void RollsTest()
        {
            // TODO unit test for the property 'Rolls'
        }

    }

}
