/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TeamDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamDetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamDetail
        //private TeamDetail instance;

        public TeamDetailTests()
        {
            // TODO uncomment below to create an instance of TeamDetail
            //instance = new TeamDetail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamDetail
        /// </summary>
        [Fact]
        public void TeamDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamDetail
            //Assert.IsInstanceOfType<TeamDetail> (instance, "variable 'instance' is a TeamDetail");
        }


        /// <summary>
        /// Test the property 'SelfUrl'
        /// </summary>
        [Fact]
        public void SelfUrlTest()
        {
            // TODO unit test for the property 'SelfUrl'
        }
        /// <summary>
        /// Test the property 'MembersUrl'
        /// </summary>
        [Fact]
        public void MembersUrlTest()
        {
            // TODO unit test for the property 'MembersUrl'
        }
        /// <summary>
        /// Test the property 'PoliciesUrl'
        /// </summary>
        [Fact]
        public void PoliciesUrlTest()
        {
            // TODO unit test for the property 'PoliciesUrl'
        }
        /// <summary>
        /// Test the property 'AdminsUrl'
        /// </summary>
        [Fact]
        public void AdminsUrlTest()
        {
            // TODO unit test for the property 'AdminsUrl'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Fact]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }
        /// <summary>
        /// Test the property 'MemberCount'
        /// </summary>
        [Fact]
        public void MemberCountTest()
        {
            // TODO unit test for the property 'MemberCount'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Fact]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'IsDefaultTeam'
        /// </summary>
        [Fact]
        public void IsDefaultTeamTest()
        {
            // TODO unit test for the property 'IsDefaultTeam'
        }

    }

}
