/* 
 * VictorOps API
 *
 * This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMaintenanceModeApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get an organization&#39;s current maintenance mode state
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <returns>MaintenanceModeState</returns>
        MaintenanceModeState ApiPublicV1MaintenancemodeGet (string xVOApiId, string xVOApiKey);

        /// <summary>
        /// Get an organization&#39;s current maintenance mode state
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <returns>ApiResponse of MaintenanceModeState</returns>
        ApiResponse<MaintenanceModeState> ApiPublicV1MaintenancemodeGetWithHttpInfo (string xVOApiId, string xVOApiKey);
        /// <summary>
        /// End maintenance mode for routing keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="maintenancemodeid">The id of the maintenance mode found in the active maintenance mode object</param>
        /// <returns>MaintenanceModeState</returns>
        MaintenanceModeState ApiPublicV1MaintenancemodeMaintenancemodeidEndPut (string xVOApiId, string xVOApiKey, string maintenancemodeid);

        /// <summary>
        /// End maintenance mode for routing keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="maintenancemodeid">The id of the maintenance mode found in the active maintenance mode object</param>
        /// <returns>ApiResponse of MaintenanceModeState</returns>
        ApiResponse<MaintenanceModeState> ApiPublicV1MaintenancemodeMaintenancemodeidEndPutWithHttpInfo (string xVOApiId, string xVOApiKey, string maintenancemodeid);
        /// <summary>
        /// Start maintenance mode for routing keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="body"></param>
        /// <returns>MaintenanceModeState</returns>
        MaintenanceModeState ApiPublicV1MaintenancemodeStartPost (string xVOApiId, string xVOApiKey, InlineObject body);

        /// <summary>
        /// Start maintenance mode for routing keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of MaintenanceModeState</returns>
        ApiResponse<MaintenanceModeState> ApiPublicV1MaintenancemodeStartPostWithHttpInfo (string xVOApiId, string xVOApiKey, InlineObject body);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMaintenanceModeApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get an organization&#39;s current maintenance mode state
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <returns>Task of MaintenanceModeState</returns>
        System.Threading.Tasks.Task<MaintenanceModeState> ApiPublicV1MaintenancemodeGetAsync (string xVOApiId, string xVOApiKey);

        /// <summary>
        /// Get an organization&#39;s current maintenance mode state
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <returns>Task of ApiResponse (MaintenanceModeState)</returns>
        System.Threading.Tasks.Task<ApiResponse<MaintenanceModeState>> ApiPublicV1MaintenancemodeGetAsyncWithHttpInfo (string xVOApiId, string xVOApiKey);
        /// <summary>
        /// End maintenance mode for routing keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="maintenancemodeid">The id of the maintenance mode found in the active maintenance mode object</param>
        /// <returns>Task of MaintenanceModeState</returns>
        System.Threading.Tasks.Task<MaintenanceModeState> ApiPublicV1MaintenancemodeMaintenancemodeidEndPutAsync (string xVOApiId, string xVOApiKey, string maintenancemodeid);

        /// <summary>
        /// End maintenance mode for routing keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="maintenancemodeid">The id of the maintenance mode found in the active maintenance mode object</param>
        /// <returns>Task of ApiResponse (MaintenanceModeState)</returns>
        System.Threading.Tasks.Task<ApiResponse<MaintenanceModeState>> ApiPublicV1MaintenancemodeMaintenancemodeidEndPutAsyncWithHttpInfo (string xVOApiId, string xVOApiKey, string maintenancemodeid);
        /// <summary>
        /// Start maintenance mode for routing keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="body"></param>
        /// <returns>Task of MaintenanceModeState</returns>
        System.Threading.Tasks.Task<MaintenanceModeState> ApiPublicV1MaintenancemodeStartPostAsync (string xVOApiId, string xVOApiKey, InlineObject body);

        /// <summary>
        /// Start maintenance mode for routing keys
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (MaintenanceModeState)</returns>
        System.Threading.Tasks.Task<ApiResponse<MaintenanceModeState>> ApiPublicV1MaintenancemodeStartPostAsyncWithHttpInfo (string xVOApiId, string xVOApiKey, InlineObject body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMaintenanceModeApi : IMaintenanceModeApiSync, IMaintenanceModeApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MaintenanceModeApi : IMaintenanceModeApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceModeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MaintenanceModeApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceModeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MaintenanceModeApi(String basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceModeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MaintenanceModeApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceModeApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MaintenanceModeApi(Org.OpenAPITools.Client.ISynchronousClient client,Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get an organization&#39;s current maintenance mode state 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <returns>MaintenanceModeState</returns>
        public MaintenanceModeState ApiPublicV1MaintenancemodeGet (string xVOApiId, string xVOApiKey)
        {
             Org.OpenAPITools.Client.ApiResponse<MaintenanceModeState> localVarResponse = ApiPublicV1MaintenancemodeGetWithHttpInfo(xVOApiId, xVOApiKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get an organization&#39;s current maintenance mode state 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <returns>ApiResponse of MaintenanceModeState</returns>
        public Org.OpenAPITools.Client.ApiResponse< MaintenanceModeState > ApiPublicV1MaintenancemodeGetWithHttpInfo (string xVOApiId, string xVOApiKey)
        {
            // verify the required parameter 'xVOApiId' is set
            if (xVOApiId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiId' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeGet");

            // verify the required parameter 'xVOApiKey' is set
            if (xVOApiKey == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiKey' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeGet");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (xVOApiId != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiId)); // header parameter
            if (xVOApiKey != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiKey)); // header parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get< MaintenanceModeState >("/api-public/v1/maintenancemode", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPublicV1MaintenancemodeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get an organization&#39;s current maintenance mode state 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <returns>Task of MaintenanceModeState</returns>
        public async System.Threading.Tasks.Task<MaintenanceModeState> ApiPublicV1MaintenancemodeGetAsync (string xVOApiId, string xVOApiKey)
        {
             Org.OpenAPITools.Client.ApiResponse<MaintenanceModeState> localVarResponse = await ApiPublicV1MaintenancemodeGetAsyncWithHttpInfo(xVOApiId, xVOApiKey);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get an organization&#39;s current maintenance mode state 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <returns>Task of ApiResponse (MaintenanceModeState)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<MaintenanceModeState>> ApiPublicV1MaintenancemodeGetAsyncWithHttpInfo (string xVOApiId, string xVOApiKey)
        {
            // verify the required parameter 'xVOApiId' is set
            if (xVOApiId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiId' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeGet");

            // verify the required parameter 'xVOApiKey' is set
            if (xVOApiKey == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiKey' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeGet");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (xVOApiId != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiId)); // header parameter
            if (xVOApiKey != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiKey)); // header parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<MaintenanceModeState>("/api-public/v1/maintenancemode", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPublicV1MaintenancemodeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// End maintenance mode for routing keys 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="maintenancemodeid">The id of the maintenance mode found in the active maintenance mode object</param>
        /// <returns>MaintenanceModeState</returns>
        public MaintenanceModeState ApiPublicV1MaintenancemodeMaintenancemodeidEndPut (string xVOApiId, string xVOApiKey, string maintenancemodeid)
        {
             Org.OpenAPITools.Client.ApiResponse<MaintenanceModeState> localVarResponse = ApiPublicV1MaintenancemodeMaintenancemodeidEndPutWithHttpInfo(xVOApiId, xVOApiKey, maintenancemodeid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// End maintenance mode for routing keys 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="maintenancemodeid">The id of the maintenance mode found in the active maintenance mode object</param>
        /// <returns>ApiResponse of MaintenanceModeState</returns>
        public Org.OpenAPITools.Client.ApiResponse< MaintenanceModeState > ApiPublicV1MaintenancemodeMaintenancemodeidEndPutWithHttpInfo (string xVOApiId, string xVOApiKey, string maintenancemodeid)
        {
            // verify the required parameter 'xVOApiId' is set
            if (xVOApiId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiId' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeMaintenancemodeidEndPut");

            // verify the required parameter 'xVOApiKey' is set
            if (xVOApiKey == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiKey' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeMaintenancemodeidEndPut");

            // verify the required parameter 'maintenancemodeid' is set
            if (maintenancemodeid == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'maintenancemodeid' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeMaintenancemodeidEndPut");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (maintenancemodeid != null)
                localVarRequestOptions.PathParameters.Add("maintenancemodeid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(maintenancemodeid)); // path parameter
            if (xVOApiId != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiId)); // header parameter
            if (xVOApiKey != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiKey)); // header parameter


            // make the HTTP request
            var localVarResponse = this.Client.Put< MaintenanceModeState >("/api-public/v1/maintenancemode/{maintenancemodeid}/end", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPublicV1MaintenancemodeMaintenancemodeidEndPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// End maintenance mode for routing keys 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="maintenancemodeid">The id of the maintenance mode found in the active maintenance mode object</param>
        /// <returns>Task of MaintenanceModeState</returns>
        public async System.Threading.Tasks.Task<MaintenanceModeState> ApiPublicV1MaintenancemodeMaintenancemodeidEndPutAsync (string xVOApiId, string xVOApiKey, string maintenancemodeid)
        {
             Org.OpenAPITools.Client.ApiResponse<MaintenanceModeState> localVarResponse = await ApiPublicV1MaintenancemodeMaintenancemodeidEndPutAsyncWithHttpInfo(xVOApiId, xVOApiKey, maintenancemodeid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// End maintenance mode for routing keys 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="maintenancemodeid">The id of the maintenance mode found in the active maintenance mode object</param>
        /// <returns>Task of ApiResponse (MaintenanceModeState)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<MaintenanceModeState>> ApiPublicV1MaintenancemodeMaintenancemodeidEndPutAsyncWithHttpInfo (string xVOApiId, string xVOApiKey, string maintenancemodeid)
        {
            // verify the required parameter 'xVOApiId' is set
            if (xVOApiId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiId' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeMaintenancemodeidEndPut");

            // verify the required parameter 'xVOApiKey' is set
            if (xVOApiKey == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiKey' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeMaintenancemodeidEndPut");

            // verify the required parameter 'maintenancemodeid' is set
            if (maintenancemodeid == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'maintenancemodeid' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeMaintenancemodeidEndPut");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (maintenancemodeid != null)
                localVarRequestOptions.PathParameters.Add("maintenancemodeid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(maintenancemodeid)); // path parameter
            if (xVOApiId != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiId)); // header parameter
            if (xVOApiKey != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiKey)); // header parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<MaintenanceModeState>("/api-public/v1/maintenancemode/{maintenancemodeid}/end", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPublicV1MaintenancemodeMaintenancemodeidEndPut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Start maintenance mode for routing keys 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="body"></param>
        /// <returns>MaintenanceModeState</returns>
        public MaintenanceModeState ApiPublicV1MaintenancemodeStartPost (string xVOApiId, string xVOApiKey, InlineObject body)
        {
             Org.OpenAPITools.Client.ApiResponse<MaintenanceModeState> localVarResponse = ApiPublicV1MaintenancemodeStartPostWithHttpInfo(xVOApiId, xVOApiKey, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Start maintenance mode for routing keys 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of MaintenanceModeState</returns>
        public Org.OpenAPITools.Client.ApiResponse< MaintenanceModeState > ApiPublicV1MaintenancemodeStartPostWithHttpInfo (string xVOApiId, string xVOApiKey, InlineObject body)
        {
            // verify the required parameter 'xVOApiId' is set
            if (xVOApiId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiId' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeStartPost");

            // verify the required parameter 'xVOApiKey' is set
            if (xVOApiKey == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiKey' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeStartPost");

            // verify the required parameter 'body' is set
            if (body == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'body' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeStartPost");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (xVOApiId != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiId)); // header parameter
            if (xVOApiKey != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiKey)); // header parameter
            localVarRequestOptions.Data = body;


            // make the HTTP request
            var localVarResponse = this.Client.Post< MaintenanceModeState >("/api-public/v1/maintenancemode/start", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPublicV1MaintenancemodeStartPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Start maintenance mode for routing keys 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="body"></param>
        /// <returns>Task of MaintenanceModeState</returns>
        public async System.Threading.Tasks.Task<MaintenanceModeState> ApiPublicV1MaintenancemodeStartPostAsync (string xVOApiId, string xVOApiKey, InlineObject body)
        {
             Org.OpenAPITools.Client.ApiResponse<MaintenanceModeState> localVarResponse = await ApiPublicV1MaintenancemodeStartPostAsyncWithHttpInfo(xVOApiId, xVOApiKey, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Start maintenance mode for routing keys 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xVOApiId">Your API ID</param>
        /// <param name="xVOApiKey">Your API Key</param>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (MaintenanceModeState)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<MaintenanceModeState>> ApiPublicV1MaintenancemodeStartPostAsyncWithHttpInfo (string xVOApiId, string xVOApiKey, InlineObject body)
        {
            // verify the required parameter 'xVOApiId' is set
            if (xVOApiId == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiId' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeStartPost");

            // verify the required parameter 'xVOApiKey' is set
            if (xVOApiKey == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xVOApiKey' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeStartPost");

            // verify the required parameter 'body' is set
            if (body == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'body' when calling MaintenanceModeApi->ApiPublicV1MaintenancemodeStartPost");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (xVOApiId != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiId)); // header parameter
            if (xVOApiKey != null)
                localVarRequestOptions.HeaderParameters.Add("X-VO-Api-Key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVOApiKey)); // header parameter
            localVarRequestOptions.Data = body;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<MaintenanceModeState>("/api-public/v1/maintenancemode/start", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiPublicV1MaintenancemodeStartPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
